theme: jekyll-theme-minimal
title: SentinelByte - Tech Insights
description: Technical content and hands-on guides on cybersecurity, automation, AI/ML, cloud, and more.
url: "https://sentinelbyte.github.io"
author: "Dan Cohen Vaxman (SentinelByte)"
github_username: SentinelByte

# Social links
github_username: SentinelByte

# Social links (optional)
linkedin: https://www.linkedin.com/in/35b767173/
rss: rss

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude these files from the site build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
