# Site settings
theme: jekyll-theme-minimal
title: SentinelByte
description: Technical content and hands-on guides on cybersecurity, automation, AI/ML, cloud, pipelines and more.
permalink: /:categories/:title/